export const SECTIONS = [
  { slug: "", label: "Overview", code: "00_PROJECT" },
  { slug: "intake", label: "Intake", code: "INTAKE" },
  { slug: "business", label: "Business Requirement", code: "01_BUSINESS_REQUIREMENT" },
  { slug: "inventory", label: "Data Inventory", code: "02_DATA_INVENTORY" },
  { slug: "domains", label: "Domain Registry", code: "DDR" },
  { slug: "dictionary", label: "Data Dictionary", code: "03_DATA_DICTIONARY" },
  { slug: "profiling", label: "Profiling", code: "11_DATA_PROFILING" },
  { slug: "mapping", label: "Mapping", code: "04_DATA_MAPPING" },
  { slug: "canonical", label: "Canonical Model", code: "05_CANONICAL_MODEL" },
  { slug: "ontology", label: "Ontology", code: "06_ONTOLOGY" },
  { slug: "contracts", label: "Data Contract", code: "07_DATA_CONTRACT" },
  { slug: "systems", label: "System / API", code: "08_SYSTEM_INVENTORY" },
  { slug: "workflows", label: "Workflow", code: "09_WORKFLOW" },
  { slug: "samples", label: "Sample Data", code: "10_SAMPLE_DATA" },
  { slug: "security", label: "Security", code: "12_SECURITY" },
  { slug: "gaps", label: "Gap & Decision Log", code: "13_GAP_AND_DECISION_LOG" },
  { slug: "architecture", label: "Architecture", code: "14_ARCHITECTURE" },
  { slug: "documents", label: "Generated Documents", code: "VIEWS" },
  { slug: "impact", label: "Change Impact", code: "IMPACT" },
  { slug: "lineage", label: "Lineage", code: "TRACE" },
  { slug: "package", label: "Customer Data Package", code: "EXPORT" },
] as const;
